---
- src: kamaln7.swapfile
- src: T2L.php
  version: 1.1.1
- src: T2L.composer
  version: 2.0.2
- src: T2L.composer-global-packages
  version: 2.0.2
- src: T2L.java
  version: 1.0.1
- src: T2L.solr
  version: 1.2.0
