---
# Install apache2.
- name: Install Apache2 web server
  apt:
    name: apache2
    state: present
    update_cache: yes
    cache_valid_time: 86400

# Configure enabled modules.
- name: Enable Apache2 modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
      - rewrite
  notify:
    - Restart Apache2 web server

# Configure web server.
- name: Set correct DirectoryIndex
  lineinfile:
    dest: /etc/apache2/mods-available/dir.conf
    regexp: "DirectoryIndex"
    line: "DirectoryIndex index.php index.html"

# Disable default virtual host created on Ubuntu/Debian.
- name: Disable default virtual host.
  command: a2dissite 000-default
  register: apache2_disable_default_virtual_host_result
  changed_when: "'Site 000-default disabled.' in apache2_disable_default_virtual_host_result.stdout"
  notify:
    - Restart Apache2 web server

# Add custom virtual host.
- name: Add custom virtual host.
  template:
    src: "vhost-apache24.conf.j2"
    dest: "/etc/apache2/sites-available/default.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - Restart Apache2 web server

- name: Enable custom virtual host.
  command: a2ensite default
  register: apache2_enable_custom_virtual_host_result
  changed_when: "'Enabling site default.' in apache2_enable_custom_virtual_host_result.stdout"
  notify:
    - Restart Apache2 web server

# Ensure that apache2 daemon starts with the system.
- name: Ensure Apache2 is started and enabled on boot.
  service:
    name: apache2
    state: started
    enabled: yes
