---
vagrant:
  box: "ubuntu/xenial64"
  box_version: ">=0"
  box_check_update: false
  hostname: "molecule"
  ip_address: "10.10.10.10"
  host_aliases:
    - molecule.molecule
  base_directory: /var/www/draft
  synced_folder_options:
    type: nfs
    create: true

virtualbox:
  name: "molecule"
  cpus: 2
  memory: 1024
  cpuexecutioncap: 100

ansible:
  version: 2.6.*

draft_features:
  - swapfile
  - mailhog
  - git_config
  - apache2
  - mysql
  - php
  - composer
  - java
  - solr
